input {
    file {
        path => "/home/cloud_user/elk/sales.csv"
        start_position => "beginning"
    }
}
filter {
    csv {
        columns => ["product", "stock", "price"]
        skip_header => true
        convert => {
          "stock" => "integer"
          "price" => "float"
        }
    }
}
output {
    stdout { }
    elasticsearch {
       hosts => ["https://logstash:passwd123@172.31.31.246:9200"]
       ssl_certificate_authorities => "/home/cloud_user/http_ca.crt"
       ssl_verification_mode => none
       ssl_enabled => true
       index => "udemy-log"
       doc_as_upsert => true
    }
}
