input {
    file {
        path => "/home/cloud_user/elk/sales_example_2.csv"
        start_position => "beginning"
    }
}
filter {
    csv {
        columns => ["product", "stock", "price", "is_true"]
        convert => {
          "price" => "float"
          "is_true" => "boolean"
        }
    }
}
output {
    stdout { }
}
