#input {
#    udp {
#      port => "5005"
#      type => "netflow"
#    }
#}
input { stdin { } }
filter {
    date {
      match => ["message", "MMM dd yyyy HH:mm:ss"]
      # Default for target is @timestamp
      target => "logdate_modified"
      locale => "en"
      timezone => "Europe/Moscow"
    }
}
output {
     stdout { }
}
