input {
    elasticsearch {
       user => "logstash"
       password => "passwd123"
       hosts => ["https://172.31.31.246:9200"]
       ssl_certificate_authorities => "/home/cloud_user/http_ca.crt"
       ssl_verification_mode => none
       ssl_enabled => true
       index => "products"
       query => '{ "query": { "match": { "Size": { "query": "XS", "operator": "or" } } } }'
       type => "my-data-elasticsearch"
    }
}
output {
    stdout { }
}
