input {
       file {
          path => "/var/log/cloud-init-output-copy.log"
          exclude => "*.gz"
          sincedb_path => "/dev/null"
          start_position => "beginning"
          type => "Logstash-File-Plugin-TEST"
       }
}
output {
       stdout { }
}
