input { stdin { } }
filter {
  grok {
     match => { "message" => '%{IPORHOST:client_ip} %{USER:ident} %{USER:auth} \[%{HTTPDATE:timestamp}\] "%{WORD:verb} %{DATA:request} HTTP/%{NUMBER:http_version}" %{NUMBER:response:int} (?:-|%{NUMBER:bytes:int}) %{QS:reffer} %{QS:agent}' }
  }
  date {
    match => ["timestamp", "dd/MMM/YYYY:HH:mm:ss Z"]
  }
  geoip {
    source => "client_ip"
    target => "client"
  }
  useragent {
    source => "agent"
    target => "useragent"
  }
}
output {
  stdout { }
  elasticsearch {
    hosts => ["https://logstash:passwd123@172.31.31.246:9200"]
    ssl_certificate_authorities => "/home/cloud_user/http_ca.crt"
    ssl_verification_mode => none
    ssl_enabled => true
    index => "udemy-log"
    doc_as_upsert => true
  }
}
# The example of the string: 
#83.149.9.216 - - [29/May/2025:13:05:03 +0000] "GET /presentation/logstash-monitorma-2013/images/kibana-search.png HTTP/1.1" 200 203023 "http://semicomplete.com/presentations/logstash-monitorama-2013/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_1) AppleWebKit/537.36 Chrome/32.0.1700.77 Safari/537.36"
