input {
    file {
        path => "/home/cloud_user/grok_http.log"
        start_position => "beginning"
    }
}
filter {
  grok {
    match => { "message" => "%{IP:client} %{WORD:method} %{URIPATHPARAM:request} %{NUMBER:bytes} %{NUMBER:duration}" }
  }
  date {
    match => ["syslog_timestamp", "MMM d HH:mm:SS", "MMM dd HH:mm:ss"]
  }
}
output {
  stdout { }
}
