input { stdin { } }
filter {
  grok {
     match => { "message" => "%{SYSLOGTIMESTAMP:syslog_timestamp} %{SYSLOGHOST:syslog_hostname} %{DATA:syslog_program}(?:\[%{POSINT:syslog_pid}])?: %{GREEDYDATA:syslog_message}" }
  }
  date {
    match => ["syslog_timestamp", "MMM d HH:mm:SS", "MMM dd HH:mm:ss"]
  }
}
output {
  stdout { }
  elasticsearch {
    hosts => ["https://logstash:passwd123@172.31.31.246:9200"]
    ssl_certificate_authorities => "/home/cloud_user/http_ca.crt"
    ssl_verification_mode => none
    ssl_enabled => true
    index => "udemy-log"
    doc_as_upsert => true
  }
}
# The example of the string Jun 10 04:04:01 lvps109-104-93-171 postfix/smtpd[11105]: connect from mail-we0-f196.google.com[74.125.82.196]
