input {
    file {
        path => "/home/cloud_user/grok_http.log"
        start_position => "beginning"
    }
}
filter {
  mutate {
    add_field => {
      "foo_%{message}" => "Hello world, from %{host}"
      "created_field" => "new_static_value"
    }
#    convert => {"message" => "integer"} #Will change the whole data of message field to the zero number in this example
#    gsub => ["message", "/", "_"] #Will change the forward slash to the underscore
#    uppercase => ["message"] # Will change data from messsage field to the uppercase format
#    remove_field => ["foo_%{message}", "my_etraneous_field"] # Will remove only one filed due to second one doesn't exist
#    rename => {"message" => "new_message"} # Will rename existing message filed to the new one
    replace => {"message" => "My new message and the new var foo_%{message}"} #Will replace existing data from the message field to the another one
 }
}
output{
  stdout { }
}
