input {
    jdbc {
        jdbc_connection_string => "jdbc:mysql://172.31.30.17:3306/elastic_db"
        jdbc_user => "elasticsearch"
        jdbc_password => "passwd123"
        jdbc_driver_library => "/usr/share/java/mysql-connector-j.jar"
        jdbc_driver_class => "com.mysql.cj.jdbc.Driver"
        statement => "SELECT * FROM todos WHERE ID > :sql_last_value"
        use_column_value => true
        tracking_column => "id"
        tracking_column_type => numeric
        schedule => "* * * * *"
    }
}
output {
    stdout { }
    elasticsearch {
       hosts => ["https://logstash:passwd123@172.31.31.246:9200"]
       ssl_certificate_authorities => "/home/cloud_user/http_ca.crt"
       ssl_verification_mode => none
       ssl_enabled => true
       index => "mysql_2_es"
       doc_as_upsert => true
    }
}
