input {
  stdin { }
}
filter {
  range {
    ranges => [ "message", 0, 10, "tag:short",
                "message", 11, 40, "tag:medium",
                "message", 41, 70, "tag: long",
                "message", 71, 1000, "drop" ]
  }
}
output { stdout { } }             
