input {
  tcp {
    port => "5000"
    type => "tcp message"
  }
  udp {
    port => "5001"
    type => "udp message"
  }
}
filter {
  grok {
    match => { "message" => "%{WORD:firstname} %{WORD:lastname} %{NUMBER:salary}" }
  }
}
output {
  stdout { }
}
# For test
# TCP: echo "Alberto Pinto 30000" | nc localhost 5000
# UDP: echo "Tetra Search 500" | nc -u 172.31.19.250 5001
