input { stdin { } }
filter {
  translate {
    source => "message"
    target => "new_message"
    dictionary => { 
      "100" => "One Hundred"
      "101" => "More than a Hundred"
      "merci" => "thank you"
      "hola" => "Hello"
      "this version" => "that version"
   }
#   field => ["ping", "pong"]
 }
}
output { stdout { } }
